name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.0.3
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
